### PR TITLE
Revert #39 (agnostic shebang)

### PR DESCRIPTION
**Pull request by IvanSanchez**
Request to revert #39. Apparently it's biting some people (me and somebody in #43 included).

### CODE REVIEW

**Comment by dereckson** [comment]
That's not a solution, as you allow one group to run it, but not the other. You wouldn't be able to run it on Mac OS X or FreeBSD anymore for example.

So, instead, we could offer a shebang taking care of everything.

Could you test this?

```
#!/bin/sh
#! −*−perl−*−
eval 'exec perl −x −wsS $0 ${1+"$@"}'
    if 0;
```

**Comment by atomicules** [comment]
On 14-Dec-2015 12:11:16, Sébastien Santoro wrote:

> So, instead, we could offer a shebang taking care of everything.

Sounds terribly hacky and therefore utterly suitable for oysttyer, but 
also at the same time, if this is so tricky to get right, why don't we 
drop the shebang altogether? It's not too much hassle to type `perl 
/path/to/oysttyer.pl`

Just an opinion/thought. Not an order.

**Comment by mscman** [comment]
Arguing shebangs is a fun one. Even the solution @dereckson posted won't prevent path issues. Multiple perl installs is not an easy thing to manage.

The biggest advantage to the `#!/bin/sh` solution is that it allows the user to pass other arguments to perl, such as enabling warnings. 

We could also leave it as `#!/usr/bin/env perl` and tell users to make sure that the path to their desired perl is first in their path (i.e. launch with `PATH=/path/to/perl:$PATH`). We could also provide a wrapper script to launch oystter for them and get a little more clever with settings to the path to perl. 

Unfortunately with the variety of ways to install perl, I don't think we'll find a one-size-fits-all solution. We're going to have to focus on good documentation and a good troubleshooting guide to help people who hit these issues.

**Comment by classilla** [comment]
You'll still need the -s option, or people won't be able to pass things on the command line (unless you changed the BEGIN block to do the parsing manually).

**Comment by realchrisolin** [comment]
Thought I'd leave some unbiased comments/advice/slight criticism here. I forked this repo and ran into an issue trying to start oysttyer in CentOS 7, even though perl is in $PATH.

```
~/oysttyer(branch:master) » ./oysttyer.pl
/usr/bin/env: perl -s: No such file or directory
------------------------------------------------------------
~/oysttyer(branch:master) » type perl
perl is /usr/bin/perl
------------------------------------------------------------
~/oysttyer(branch:master) » perl -v

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 28 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

I ended up adding the following to ~/.aliases, which works fine as a workaround

```
alias oysttyer='perl $HOME/oysttyer/oysttyer.pl'
```

**Comment by atomicules** [comment]
Note that I tried the syntax (and variations on) from @dereckson and I couldn't get that to work.

For now we are going back to `/usr/bin/perl` so we can legitimately used the `-s` flag, but I've opened #67 for a longer term fix. However, even using `/usr/bin/env` won't work for everyone.

**Pull request closed without merging**
