### PR TITLE
More extended tweet fixes.

### PR DESCRIPTION
**Pull request by myshkin**
Added grabjson() calls to normalizejson() to populate RT and QT hashes.
Made destroy_all_tco() check additional entities fields.
Added some superfields to the dumper.

Here's what I'm currently running to address #83. Seems okay so far in very limited testing.

### CODE REVIEW

**Comment by funnelfiasco** [comment]
Looking good so far, but I see the calls to `&fix_geo_api_data` and `&destroy_all_tco` are gone. This seems to be working, but I wonder if there's something that I'm missing.

The repeated calls to grabjson are making `/again` noticably slower, but I guess that's something we'll have to deal with. My big concern is how it will affect rate limits, but I don't have a better answer at the moment.

**Comment by myshkin** [comment]
I figured `grabjson()` would call `normalizejson()`, which would handle geo data and t.co. 

I would certainly rather not call `grabjson()` again. The API documentation seems to indicate that the `retweeted_status` field should contain a full tweet object already, but then something was killing the `text` field.

**Comment by funnelfiasco** [comment]
Ah, you're right. I missed that on first look. I drew the same conclusion from looking at the API docs, so I don't know what's going on. I'm inclined to accept this PR and just go with it and we can optimize for performance later. I'll merge it tomorrow morning and bump the official release later this week if nobody has any brilliant ideas between now and then.

**Comment by myshkin** [comment]
Don't merge yet. I'm seeing some odd behavior, mostly (though not exclusively) related to tracking. I'm getting a lot of track results showing up as "RT @:" and so `retweeted_status` is missing both screen name and text somehow. (e.g. ID 783123339053113344) Also, I saw a quoted tweet show up but not the tweet that quoted it. It's possible a filter got in the way, but I don't think so.

What debugging tools do you use? Running with `perl -d` was a nightmare due to the curses manipulation and the multiple processes. I'd like to look at the tweet structures in real-time.

**Comment by funnelfiasco** [comment]
Right as I was about to say "hmm, I haven't seen anything like that", I saw that with status `783289711335006208`. It works when I hit it with `/thread`, so clearly we're getting there via a different route.

JSON of said tweet: https://gist.github.com/funnelfiasco/f70bc437155c2e7ebd10b632b7890179

As for debuggers, I use "run the script and see what happens", along with the jsondump plugin (https://github.com/oysttyer/oysttyer-dev).

**Comment by myshkin** [comment]
Ah, jsondump is exactly what I wanted, except that I modified it to take menu codes. I want to look at what the script has in memory, not grab the json anew.

**Comment by myshkin** [comment]
Unfortunately, I haven't seen any more blank tweets, but I have seen some quoted tweets pop up in my timeline without their accompanying base tweets. They don't show up in other clients, and so I don't know what their source is.

**Comment by myshkin** [comment]
Aha. They were quote-tweeted by a user I follow but have muted and filtered. I guess the `grabjson()` calls in `normalizejson()` inject the quoted tweets before hitting filtering.

**Comment by funnelfiasco** [comment]
I'm inclined to call it shippable then. Better support for blocking and muting is something I'd like to do for a future release, so that might be a good time to address this case.

**Comment by myshkin** [comment]
Now that I have my version of jsondump, I've reverted to the version without so many `grabjson()` calls. The blank quoted tweets have `quoted_status_id_str` but no `quoted_status`, and the blank retweets have a valid `retweeted_status->id_str` but nothing else in the `retweeted_status` hash. Strange. By contrast, fetching the tweet via ID gives a fully populated tweet object, as per the API docs. I think the problem is that the `pipet` section of the main loop (line 4287 or so) isn't grabbing all of the fields it should. I'm surprised that the streaming socket doesn't just pass JSON, but I am hesitant to make such a large change without understanding the code better. What do you think?

**Comment by funnelfiasco** [comment]
I'd like to understand the code better, too. :-)

Having the streaming socket pass JSON seems like the right long term solution, but it's probably too big a change for the time being. It definitely falls under the "lets redo a lot of this code" category. Does adding the `quoted_status` and the rest of the `retweeted_status` hash to that section make the problem go away?

If not, I vote we take your branch as is.

**Comment by myshkin** [comment]
I'm trying that out now. I had to change the separator from space to null...and I'm running afoul of API rate limits, and so it may be a little while before I have good results.

**Comment by myshkin** [comment]
Okay, give this version a try. That was a bit of a chore...turns out the packets for background fetches weren't large enough to store that many copies of the tweet. Hopefully 2k is enough. I snuck some code cleanup into this patch, too, although not a lot.

**Comment by classilla** [comment]
You _could_ pass JSON that way, but the problem which you appear to have already run into is the maximum size of IPC packets (which is system dependent). In Texapp I increased the size of the packet to 8192, with a loop that keeps grabbing data inside the background process until it gets the entire packet. You may need to do something similar if you have to add additional fields. If you wanted to pass arbitrary JSON this way it will probably need to be much larger than that.

**Comment by myshkin** [comment]
Thanks. Is increasing the packet size to 2048 bytes dangerous on the systems we intend to support, then? I could probably be more clever about what gets passed.

**Comment by funnelfiasco** [comment]
~~We could rewrite the streaming process to offer a REST endpoint and use that for all of the interprocess communication!!!!!~~

I'm running the latest version of the fix now. Looks good to me, but I'll give it a little bit just in case.

As for "the systems we intend to support", I don't think we as a project have explicitly considered what kind of systems we'll support. Certainly TTYtter put a focus on not requiring anything approaching recent Perl, hardware, etc. Personally, I like keeping that, but I'm open to breaking compatibility with older tech when it prevents us from doing something better. I won't speak for the rest of the team, though. Something we should probably think about more generally at some point.

**Comment by classilla** [comment]
I wouldn't say dangerous, but some systems will not pass more than 1K or so per transaction on the IPC pipe (i.e., if you try to read() it, you wouldn't get everything), so you will probably need a loop for highest compatibility. Even some relatively recent versions of OS X, er, macOS, whatever, had this problem.

Something like variable packet sizes could be entertained, but I'm not really sure it would be more performant because the data transfer is a very small portion of the actual overhead.

**Comment by funnelfiasco** [comment]
We're still not quite there. Some t.co links aren't being destroyed in quoted tweets. E.g. `783686992072671232` (it works if you `/again 783686992072671232` though)

**Comment by funnelfiasco** [comment]
Well I tried a few changes and only succeeded in making it worse. The non-destruction of tco only happens in (some) RTs and (some) quoted tweets. I'm inclined to call it good enough at this point. I'll merge later today.

**Comment by myshkin** [comment]
I likely won't have a chance to work on oysttyer today or tomorrow, and so if you want to go ahead, feel free. The change seems at least reasonably usable as it stands.

**Comment by myshkin** [comment]
Actually, one more quick thing to try, now that I look at it...what if, in `normalizejson()`, we move the `destroy_all_tco()` and `fix_geo_api_data()` calls to after the `if ($extended)` blocks for RTs and QTs? I bet that would do the trick.

**Comment by funnelfiasco** [comment]
It appears to do the trick. And if not, it's at least not breaking anything. I'mma call this done.

**Pull request merged**
