### PR TITLE
Multiple account configs in separate $HOME/.oysttyer/<twitter-account> directories

### PR DESCRIPTION
**Pull request by paolo-lulli**
Hello,

for personal use I find convenient to store config under a $HOME/.oysttyer/<twitter-account> dir.
You might consider that one as an improvement (or maybe not).

Regards,
PL

### CODE REVIEW

**Comment by funnelfiasco** [comment]
It's an interesting idea, but I'd like to put it on hold a bit to get more commentary from the rest of the community. Like you, I run several accounts simultaneously, and this seems marginally better than using `-rc=blah` when launching. The downsides are:
1. We go from one executable to three (though your two new ones are optional)
2. We break compatibility with people migrating from TTYtter or older versions of Oysttyer.

I'm not sure how much we care, but it's not a decision I'd want ot make lightly.

**Comment by tjharman** [comment]
I always like the idea that Oysttyer/TTYtter was the tool and you had to wrap your own cleverness into it.  Therefore I don't think this is a great idea, though of course I can see why you'd want it.  I've always been fine with -rc= for multiple accounts.

**Comment by classilla** [comment]
Old fart drive-by note: by running "perl" from the launcher script, you might not get argument parsing (no -s) and it might not be the "perl" the user expects to be running Oysttyer, so you may have edge cases with, say, T::RL::TTYtter installed on the Perl in the shebang line but not in the Perl the launcher actually runs.

**Comment by squaregoldfish** [comment]
Wouldn't it be possible to support both methods? If the .oysttyer directory exists use that, otherwise fall back to the .oysttyerrc file? (Or perhaps the other way round would be better.)

I'm ambivalent on the change itself - either way would work fine for me.

**Comment by jasonwryan** [comment]
Another vote for the status quo. *But* if you are going to change it, for the love of deity, please honour `$XDG_CONFIG_HOME`.

**Comment by funnelfiasco** [comment]
The community seems generally in favor of not adopting this, but I really appreciate the contribution.

**Pull request closed without merging**
