### PR TITLE
replace "oysttyer" with the username of who you're signed in as

### PR DESCRIPTION
**Pull request by realchrisolin**
I made this change in TTYtter previously and am now making it again for two reasons:
- It's slightly more useful having the username you're signed into in the bottom left corner versus the name of the program.
- I manage a personal Twitter account and company Twitter account in separate console (tmux) windows. [Knowing who I'm tweeting as is important.](http://money.cnn.com/galleries/2011/technology/1104/gallery.social_media_controversies/3.html)

Since it's a minor change, it doesn't necessarily have to be an upstream "feature", but I thought I'd submit a pull request anyways. I'll leave the choice of merging it or not to you.

### CODE REVIEW

**Comment by IvanSanchez** [comment]
I like it. I'm just wondering if it should be the default, or be behind an option.

**Comment by atomicules** [comment]
I like this too, but think it should be an option.

I could work on merging this in and amending it to be optional, but I 
can't do that today so if someone else wants to beat me to it, feel 
free.

**Comment by funnelfiasco** [comment]
I should have some time today to take a crack at it.

**Comment by realchrisolin** [comment]
Perl isn't my strong suite, but I can try. Worst case, it's not pretty and someone comes up with a better implementation.

**Comment by realchrisolin** [comment]
Or actually, worst case is I can't get it to work. I added in a new boolean option under %opts_boolean, defined it with the rest of the boolean variables, then used an if statement to set the prompt prefix, which is now null when trying to set the prompt prefix based on the value of the boolean option.

I'll keep at it, but I managed to hit the API rate limit quitting oysttyer and starting it back up repeatedly, so I'll have to give it a little bit before I can test what I've done since. You can find it in https://github.com/AWildColin/oysttyer/commit/852181c6b667b2118efeb465927462704ad85c49

**Comment by realchrisolin** [comment]
I was able to test it and the prompt is being set correctly, but it's not setting the prompt prefix correctly if showusername=0 in .oysttyerrc. I'll keep at it.

**Comment by realchrisolin** [comment]
Confirmed working. By default, the "oysttyer" prompt prefix is displayed, but setting the showusername boolean in oysttyerrc will replace it with the username of the currently signed in user. If anyone has a better way of implementing this, please comment.

**Comment by funnelfiasco** [comment]
Looks good to me! I'll merge it and anyone who runs agains the devel version can try it out until the next release (whenever that is)

**Pull request merged**
