### PR TITLE
Switched to extended mode to display truncated tweets in full.

### PR DESCRIPTION
**Pull request by myshkin**
For API details, see
https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

I've been running these changes locally for a day or so, but haven't looked too closely at DMs or corner cases.

### CODE REVIEW

**Comment by funnelfiasco** [comment]
@myshkin awesome. I count 25 instances of 'full_text' in your patch, which is 2 fewer than my blind find-and-replace. I'll run with your patch for a day or two and merge it if everything looks good.

**Comment by funnelfiasco** [comment]
@myshkin have you tried it in compatibility mode? I think I'll probably have to change your patch a bit to allow for either mode. (I'm not entirely sure why someone would choose to continue using compatibility mode, but they might have some old plugins that don't handle the new tweets correctly).

I'm inclined to make extended mode opt-in for a while and change it to the default after it's been out in the wild a bit more (and to give people with plugins time to update their plugins).

**Comment by myshkin** [comment]
@funnelfiasco One of the instances is in standarddm(); oddly, I couldn't get text of DMs from full_text, even though I changed get_dm(). Maybe I mixed up my test versions. I'm not sure what the other instance is.

I also haven't tried compatibility mode. It should be reasonably straightforward to pull full_text from the extended_tweet field instead. If you prefer, we can back out most of these changes and just put the full_text field in $w->{'text'} in get_tweet(). That could preserve more backwards compatibility with plugins.

**Comment by funnelfiasco** [comment]
I've been running your patch and it seems to work except for _replying_ to DMs. Sending and receiving works, but not replying. Weird. Anyway, I'm going to turn your changes into an optional setting and if I still see that behavior, I'll take a closer look.

**Comment by funnelfiasco** [comment]
I figured out the issue with replying to DMs: there was one place that should have still been 'text' instead of 'full_text'. How I loathe the implementation of this API change.

Anyway, I took your patch and incorporated it into the branch I had started for #83. There are still a few bugs to work out, unrelated to your changes, but to keep everything consistent, I'm going to close this so we can keep everything in #83. Thanks for your help!

**Pull request closed without merging**
